services:
  genjibot:
    restart: unless-stopped
    container_name: genji-bot
    build: .
    environment:
      - TOKEN=${TOKEN}
      - PSQL_PASSWORD=${PSQL_PASSWORD}
      - PSQL_HOST=${PSQL_HOST}
      - PYTHON_ENV=${PYTHON_ENV}
      - GLOBAL_MULTI_BAN=${GLOBAL_MULTI_BAN}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - GENJI_API_KEY=${GENJI_API_KEY}
    networks:
      - genji-network

networks:
  genji-network:
    external: true
