services:
  genjibot:
    restart: unless-stopped
    container_name: genji-bot
    build: .
    environment:
      - TOKEN=${TOKEN}
      - PSQL_PASSWORD=${PSQL_PASSWORD}
      - PSQL_HOST=${PSQL_HOST}
      - PYTHON_ENV=${PYTHON_ENV}
      - GLOBAL_MULTI_BAN=${GLOBAL_MULTI_BAN}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - GENJI_API_KEY=${GENJI_API_KEY}
      - GENJI_PK_HTTP_USERNAME=${GENJI_PK_HTTP_USERNAME}
      - GENJI_PK_HTTP_PASSWORD=${GENJI_PK_HTTP_PASSWORD}
      - SENTRY_TOKEN=${SENTRY_TOKEN}
    networks:
      - genji-network
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
networks:
  genji-network:
    external: true
