name: genji-postgres

services:
  genji-db:
    container_name: genji-postgres
    build: .
    restart: unless-stopped
    ports:
      - 9989:5432
    volumes:
      - "$HOME/genji-postgres/:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_USER=${PSQL_USER}
    networks:
      - genji-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  genji-backup:
    image: eeshugerman/postgres-backup-s3:16
    container_name: genji-pg-backup-utility
    restart: unless-stopped
    environment:
      SCHEDULE: '@weekly'     # optional
      BACKUP_KEEP_DAYS: 7     # optional
      S3_REGION: us-west-002
      S3_ACCESS_KEY_ID: ${KEY_ID}
      S3_SECRET_ACCESS_KEY: ${KEY_SECRET}
      S3_BUCKET: genjibot-backups
      S3_PREFIX: backups
      S3_ENDPOINT: ${S3_ENDPOINT}
      POSTGRES_HOST: genji-db
      POSTGRES_DATABASE: genji
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    depends_on:
      genji-db:
        condition: service_healthy
    networks:
      - genji-network

networks:
  genji-network:
    external: true
